api_version = "2025-01"

[[extensions]]
name = "Map Discount Function"
handle = "map-discount-function"

uid = "ff98862d-7028-121a-df90-b7c9a7865777f34302b0"

type = "function"

description = "Function to apply MAP (Minimum Advertised Price) discounts"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = "npm run build"
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"